sudo: required

services: docker

before_install:
  - docker login -u "kshintani" -p "dckr_pat_vEfmks3050PC1uWrq7efam4oCiI"
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test